apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python1-monorepo-sample
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/brianwcook-tenant/monorepo-sample/python1-monorepo-sample@sha256:407364fce90e98c1b1060346b5caf83a6cbdbaac6ae6d6e5868921f1e383074e
        name: my-python
        resources: {}
status: {}
