apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python1-monorepo-sample
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/brianwcook-tenant/monorepo-sample/python1-monorepo-sample@sha256:2a24d80c6957917a4da2af4da3cc1ba452ff16473ad29b03c0b1945f9e83f063
        name: my-python
        resources: {}
status: {}
