apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python1-monorepo-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/brianwcook-tenant/monorepo-sample/python1-monorepo-sample@sha256:f93c6504cf65a2092e92d6e781dcd63a1c2ea7b149e546ed65d8f06f726008b1
        name: my-python
        resources: {}
status: {}
