apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python2-monorepo-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/brianwcook-tenant/monorepo-sample/python2-monorepo-sample@sha256:0b622e86a4c1edf8844066ad104748690c72d6a06ad72ca2f8a6838c8f9a3820
        name: my-python
        resources: {}
status: {}
