apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python2-monorepo-sample
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/brianwcook-tenant/monorepo-sample/python2-monorepo-sample@sha256:44fda1fac8d300df20d10a7cb38a1de3969847e88aa9447e6bc3a50175e09b72
        name: my-python
        resources: {}
status: {}
