apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python2-monorepo-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/brianwcook-tenant/monorepo-sample/python2-monorepo-sample@sha256:06b88600c55bd2947036ea71da549322f58f2dfc9bb47af2d87c94bc148e425d
        name: my-python
        resources: {}
status: {}
