apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python2-monorepo-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/brianwcook-tenant/monorepo-sample/python2-monorepo-sample@sha256:9c948eb84315392899100253530a30dda0a6c532dc7f04ff35a9f3e9ca2fda38
        name: my-python
        resources: {}
status: {}
