apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python2-monorepo-sample
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/brianwcook-tenant/monorepo-sample/python2-monorepo-sample@sha256:3cacb77fc540574609f5f4ff0e8ca8a2b169a3226096c0d00588463e1291f781
        name: my-python
        resources: {}
status: {}
