apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python1-monorepo-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python1-monorepo-sample
    app.kubernetes.io/part-of: monorepo-sample
  name: python1-monorepo-sample
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python1-monorepo-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python1-monorepo-sample
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/brianwcook-tenant/monorepo-sample/python1-monorepo-sample@sha256:f93c6504cf65a2092e92d6e781dcd63a1c2ea7b149e546ed65d8f06f726008b1
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
