apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python2-monorepo-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python2-monorepo-sample
    app.kubernetes.io/part-of: monorepo-sample
  name: python2-monorepo-sample
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python2-monorepo-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python2-monorepo-sample
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/brianwcook-tenant/monorepo-sample/python2-monorepo-sample@sha256:05f002e6db4d9a57911cf7fda033508a8f75954a3c452c5d2e06eb06c8e75c48
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
