apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python2-monorepo-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python2-monorepo-sample
    app.kubernetes.io/part-of: monorepo-sample
  name: python2-monorepo-sample
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: python2-monorepo-sample
status:
  loadBalancer: {}
